name: asp.net ci/cd

on:
  push:
    branches:
      - master

jobs:

  docker:
    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: docker login
        run: echo "${{ secrets.docker_password }}" | docker login -u "${{ secrets.docker_username }}" --password-stdin

      - name: build image
        run: docker build -t abbas737/aspnet-kurs-isi .

      - name: push image
        run: |
          docker tag abbas737/aspnet-kurs-isi abbas737/aspnet-kurs-isi:latest
          docker push abbas737/aspnet-kurs-isi:latest

      - name: deploy ec2
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.ec2_host }}
          username: ${{ secrets.ec2_username }}
          key: ${{ secrets.ec2_ssh_key }}
          port: 22
          timeout: 15s
          debug: true

          script: |
            docker pull abbas737/aspnet-kurs-isi:latest

            docker stop aspnet-app || true
            docker rm aspnet-app || true

            docker run -d \
              --name aspnet-app \
              -p 8080:8080 \
              abbas737/aspnet-kurs-isi:latest